### ISSUE TITLE
Regular install with install.sh requires root permissions

### ISSUE THREAD

**Issue by grufwub** [Ekultek/WhatWaf#136]
Should probably mention it requires "sudo ./install.sh" in the readme.

Or for those that want a local user install (like myself):
> cd ~/your/desired/install/directory
> git clone https://github.com/ekultek/whatwaf
> pip install --user -r requirements.txt

Then either write your whatwaf bash script (usually created by install.sh) to a local user bin folder of some kind, or make an alias under the current users bashrc profile (what I personally did).

Oh and your install of beautifulsoup4 under requirements.txt didn't seem to meet all the dependencies, a pip install of bs4 instead fixed that.

Other than this haven't run into any issues yet! Works great :smiley: 

Also, feel free to call me out if I'm wrong with any of these. I just don't tend to install user applications with root privileges :stuck_out_tongue:

**Comment by TheBrownGroupOK** [comment]
/usr/local should never require privileges. It might on some systems but for the most part shouldn’t require it. Install sends everything to /usr/local so I’m guessing something about your privileges are messed up.

About the beautifulsoup4, didn’t work?

**Comment by Ekultek** [comment]
If you look [here](
https://github.com/Ekultek/WhatWaf/blob/master/install.sh#L1) everything is installed into /usr/local. It might be that I forgot to make the install executable.

Also, beautifulsoup4 didn’t work?

**Comment by grufwub** [comment]
Only root has write access under /usr/local. Other users can read / execute but not write. Looks like you still did make the file executable though!

And yep beautifulsoup4 didn't work :thinking:. Had trouble first time trying to install it from requirements.txt, it was failing module tests (I think). Then after installing 'beautifulsoup' under pip manually, when trying to run the main executable it threw up an error as you'd tried 'from bs4 import beautifulsoup' but it couldn't find bs4. So installing 'bs4' seemed to fix the issue. This might be partially down to something on my machine as the module tests were failing.

**Comment by Ekultek** [comment]
Depending on your system you are correct with /usr/local. You should give your admin account full privs to /usr/local but that’s just my opinion. 

As for bs4, that’s weird because there should t be a bs4 installer lol. Glad you got it working though

**Comment by grufwub** [comment]
Each to their own on that one I guess :stuck_out_tongue: might be worth mentioning though.

Yeah it is an odd one if I figure out why I'll be sure to let you know!

**Comment by Ekultek** [comment]
I guess I could chown the executable after installation. But if you don’t know how a file system works you probably shouldn’t be using this tool. 

I actually looked into it a little more, `pip install bs4` is just a dummy install for `pip install beautifulsoup4`. The packages are the same thing, interesting that it worked with one and not the other though. If you do figure anything out please let me know what happened.

**Comment by Ekultek** [comment]
I decided you are correct on the installing. I made it so that it installs into whatwaf's home directory under $HOME/.whatwaf/bin. Users will be responsible for sourcing their bash_profile in order for the install to become permanent. Added via https://github.com/Ekultek/WhatWaf/commit/19b68126c6c36faa5d969ea324061c20ecdaa6ab (ignore my PATH lmao)
