### ISSUE TITLE
traceback 

### ISSUE THREAD

**Issue by silverbullet-herr** [Ekultek/WhatWaf#1572]
![Screenshot_20221027-161912_Termux](https://user-images.githubusercontent.com/64875326/198332099-2a05301c-bf7c-4875-b183-06955a5a70ee.png)

help !

**Comment by Ekultek** [comment]
are you on a phone?

**Comment by silverbullet-herr** [comment]
> are you on a phone?

yessir

**Comment by Ekultek** [comment]
lol bye

**Comment by Ekultek** [comment]
I fixed your issue: https://github.com/Ekultek/WhatWaf/commit/e8003dba130d296c0ce7efe57d5ada50fe846da4
