### ISSUE TITLE
I used a phone and the author didnt immediately drop his life to help me, so he sucks!!!

### ISSUE THREAD

**Issue by silverbullet-herr** [Ekultek/WhatWaf#1573]
the script is very helpful but the author is not , he's not worth of what he wrote , he must be stolen that project for sure

**Comment by Ekultek** [comment]
I agree, this lazy bastard made a free project and his damn job keeps him away from it. What a piece of shit +1

**Comment by Ekultek** [comment]
Oh no this is staying open forever

**Comment by oldkingcone** [comment]
> the script is very helpful but the author is not , he's not worth of what he wrote , he must be stolen that project for sure

dude. i developed a brain tumor trying to read this.

**Comment by Ekultek** [comment]
problems solved: https://github.com/Ekultek/WhatWaf/commit/e8003dba130d296c0ce7efe57d5ada50fe846da4
