### ISSUE TITLE
WhatWaf is not updating

### ISSUE THREAD

**Issue by gsbuosi** [Ekultek/WhatWaf#1574]
Hi, I'm having this error at the moment of execute this command.

$ python3 ./whatwaf -u https://target_xyz.com 

![image](https://user-images.githubusercontent.com/65083456/203865426-6880669b-b280-43eb-9314-eeeeddc987f8.png)

**Comment by Ekultek** [comment]
Did you try doing what it tells you to do?

**Comment by gsbuosi** [comment]
I did and now it's says is updated... but the "Error" if can I say error..... it's there.

![image](https://user-images.githubusercontent.com/65083456/203867432-9d6556aa-614e-49d2-9bb6-92abb4d07397.png)

**Comment by Ekultek** [comment]
Change auto_update() in lib/settings.py from:

```

def auto_update():
    """
    updates from the github repo
    """

    import git

    try:
        lib.formatter.info("attempting to update WhatWaf")
        repo = git.Repo()
        current = repo.head.commit
        repo.remotes.origin.pull()
        new = repo.head.commit
        if current == new:
            lib.formatter.info("WhatWaf is the newest version")
        else:
            lib.formatter.success("successfully updated WhatWaf to the newest version")

    except:
        lib.formatter.error("unable to update WhatWaf, a new version is out attempt updating by typing `git pull`")
        pass
```

Yo:

```
def auto_update():
    pass
```

**Comment by Ekultek** [comment]
fixed via: https://github.com/Ekultek/WhatWaf/commit/38df35218c7097c5a507476fd2e757ad7c88fd84

You can run `git pull` and the `--skip-update` flag so that it won't try to update anymore.

**Comment by gsbuosi** [comment]
After had being made the changes in "lib/settings.py"

![image](https://user-images.githubusercontent.com/65083456/203869073-75c54a9f-08c2-4047-ad32-0a4b45b46066.png)

Now I'm receiving this new error message :+1: 

![image](https://user-images.githubusercontent.com/65083456/203869164-8af7daf7-5932-4de1-b7c1-d68e55c87c40.png)

**Comment by Ekultek** [comment]
you have to stash your changes.. `git stash && git pull`

**Comment by Ekultek** [comment]
I would highly suggest you Google what you're doing before using this tool.
