### ISSUE TITLE
Ouput to arbitrary directory

### ISSUE THREAD

**Issue by SolomonSklash** [Ekultek/WhatWaf#226]
I would like to request the ability to send output to an arbitrary, user specified location, rather than a fixed directory in ~. Something like `-o /path/to/file.txt`

**Comment by Ekultek** [comment]
I think this can be arranged

**Comment by Ekultek** [comment]
started to implement via https://github.com/Ekultek/WhatWaf/commit/6c110869bd46390f0cda7ce56a451e75f66e83da trying to figure out a way to do it without having to change the `HOME` variable

**Comment by Ekultek** [comment]
Alright, so via https://github.com/Ekultek/WhatWaf/commit/816cd83a73dacc9bdb5c0bd3d6c9132f527cc53f you can pass `-o` or `--output` and a directory. HOWEVER, instead of saving to that directory, it will still save to the original `HOME` variable and copy the file from there to your directory.

**Comment by Ekultek** [comment]
I'm gonna leave this open and put it on hold incase you discover any issues with this way of doing it

**Comment by Ekultek** [comment]
haven't heard any complaints
