### ISSUE TITLE
Detection fails on SSL Errors

### ISSUE THREAD

**Issue by Sylver-Dragon** [Ekultek/WhatWaf#232]
Testing against a server with a self-signed certificate appears to fail silently.  
Steps to reproduce:  
  - Execute the tool against a server with a self-signed certificate:
    `./whatwaf.py -u "https://target" -W --skip`

Result:
  - Warning received:
`[WARN] unable to determine web server`
  - A packet capture shows a client response to the server with a Fatal Alert for an Unknown CA.  

Expected Result:
  - Client ignores unknown CA and continues to connect and test
  - Tool correctly identifies webserver or any WAF

Recommended remediation:
  - in WhatWaf/lib/settings.py in the function get_page, the line:
`req = req(url, headers=headers, proxies=proxies, timeout=req_timeout, data=post_data)`
  could be modified to:
`req = req(url, headers=headers, proxies=proxies, timeout=req_timeout, data=post_data, verify=False)`
  - Since this will produce a python error, it is also necessary to add the following code near the top of settings.py near the import declarations:
`# ignore SSL Errors `
`import warnings`
`from requests.packages.urllib3.exceptions import InsecureRequestWarning`
`warnings.simplefilter('ignore',InsecureRequestWarning)`

**Comment by Ekultek** [comment]
i like it

**Comment by Ekultek** [comment]
added via https://github.com/Ekultek/WhatWaf/commit/bec9e8eda8b4195d6556ba50c83d1f730edce969 thank you!
