### ISSUE TITLE
--json option

### ISSUE THREAD

**Issue by jesuiscamille** [Ekultek/WhatWaf#25]
Hello, this is a feature proposal.

# Feature Description

When a `--json`argument is passed to WhatWaf, WhatWaf should return an array containing the list of the urls scanned with their associated WAF names and correponding tampers ( if there are ).

# Reference

[Googler usage informations](https://github.com/jarun/googler):

```
  --json                output in JSON format; implies --noprompt
```

## Example

```json
[
 {
    "url": "https://bla.com/index.html?id=1",
    "protected_by_waf": true,
    "waf_name": "IBM SECURITY WAF 1234",
    "tampers": [
        "base64encode",
        "charencode",
    ],
 },
]
```

This json syntax might be wrong, but you get the idea.

# Why ?

This option would allow other programs to use WhatWaf via the command line. To be specific, I'm planning to use WhatWaf in [AutoSQLi](https://github.com/jesuiscamille/AutoSQLi/), but at this moment the only way read WhatWaf results is to scrape it's output using some regular expressions.

I may have did some mispells in this issue, so feel free to modify it for convenience.

**Comment by Ekultek** [comment]
done via https://github.com/Ekultek/WhatWaf/commit/a9264aa33c203f29d9f5febcaa3198c8ac1ce165
