### ISSUE TITLE
Unknown Firewall

### ISSUE THREAD

**Issue by huitc** [Ekultek/WhatWaf#296]
```
Server: qianxin-waf
or
Server: 360wzws
```
360?

http://fofa.so/result?q=server%3D%3D%22360wzws%22+%7C%7C+server%3D%3D%22qianxin-waf%22&qbase64=c2VydmVyPT0iMzYwd3p3cyIgfHwgc2VydmVyPT0icWlhbnhpbi13YWYi&full=true

**Comment by Ekultek** [comment]
elaborate?

**Comment by huitc** [comment]
360 waf

**Comment by Ekultek** [comment]
How sure are you?

**Comment by Ekultek** [comment]
added via https://github.com/Ekultek/WhatWaf/commit/2d788df6a58780e8c1797bac7aac52047198206e

**Comment by huitc** [comment]
> How sure are you?

just google it~😅

**Comment by huitc** [comment]
https://fofa.so/result?qbase64=YXBwPSIzNjDnvZHnq5nljavlo6si&full=true

**Comment by Ekultek** [comment]
Firstly, if youre creating the issue its up to you to prove what youre saying. That's how this works, secondly thank you
