### ISSUE TITLE
add more Unknown Firewall

### ISSUE THREAD

**Issue by huitc** [Ekultek/WhatWaf#300]
https://fofa.so/library?utf8=%E2%9C%93&keyword=

`ctrl + c` find these:

- 安全审计
- 威胁情报产品
- 身份认证系统 ?
- 入侵防护
- 其他安全产品
- 反病毒
- 抗ddos ?
- 数据库审计 ?
- 安全文件传输 ?
- 安全基线 ?
- 堡垒机
- 日志分析 ?
- 大数据 ?
- 扫描器
- 安全软件
- 代理 ?
- 网关 ?
- 代理服务器
- Cms ?
- Saas平台 ?
- 安全检测平台
- 网站云防护
- Cdn
- 入侵检测
- 安全网关
- Waf
- 防火墙

**Comment by Ekultek** [comment]
- 安全审计
   - 威胁情报产品
   - 身份认证系统 ?
   - 入侵防护
   - 其他安全产品
   - 反病毒
   - ~~抗ddos ?~~
   - 数据库审计 ?
   - 安全文件传输 ?
   - 安全基线 ?
   - 堡垒机
   - 日志分析 ?
   - 大数据 ?
   - 扫描器
   - 安全软件
   - 代理 ?
   - 网关 ?
   - 代理服务器
   - ~~Cms ?~~ (no)
   - ~~Saas平台 ?~~ (no)
   - 安全检测平台
   - 网站云防护
   - ~~Cdn~~ (not a waf)
   - 入侵检测
   - 安全网关
   - ~~Waf~~
   - 防火墙

**Comment by Ekultek** [comment]
running the last of the queries pulled from the list you gave, thank you!

**Comment by huitc** [comment]
or.. just add `WAF` for now

like...
[safedog](https://fofa.so/result?qbase64=YXBwPSLlronlhajni5ci)
`X-Powered-By: WAF/2.0`

[360](https://fofa.so/result?qbase64=YXBwPSIzNjDkuLvmnLrljavlo6si) (other product?)
`X-Safe-Firewall: zhuji.360.cn 1.0.9.47 F1W1`
`X-Safe-Firewall: zhuji.360.cn 1.0.8.8 F1W1`
some kind like that

[Safe3](https://fofa.so/result?qbase64=YXBwPSJTYWZlM1dBRiI%3D)
or https://fofa.so/result?qbase64=c2VydmVyPT0iU2FmZTN3YWYvMi4zLjUi
```
Server: Safe3 Web Firewall
X-Powered-By: Safe3WAF/8.7.2
```

just..... dont.... do that again == ^^''
