### ISSUE TITLE
join forces?

### ISSUE THREAD

**Issue by blshkv** [Ekultek/WhatWaf#304]
It is always a pity to see several similar small projects working alone and dying alone later.
You might not agree how certain things work in other project, but it is always better to try join forces.

Have you tried?
https://github.com/EnableSecurity/wafw00f

**Comment by Ekultek** [comment]
They were actually the inspiration behind whatwaf. I didn't make whatwaf to try and "kill the others" I made it as a side project to begin with, i never expected it to be as widely used as it is now. I would love to have the oppurtunity to "join forces" as you say, however, no I have never asked

**Comment by blshkv** [comment]
well, as long as you are aware about another project... It's your call ;-)

**Comment by Ekultek** [comment]
I reached out to them, we'll see what happens. Thank you I appreciate the consideration
