### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/WhatWaf#4]
add threading the requests, this should be pretty simple since all the requests are made at once

**Comment by ZacharyGroff** [comment]
Going to work on this one tomorrow. As you said, it seems like it should be pretty simple. Is there a way I can contact you aside from Github/Twitter, email possibly? I'd love to continue helping out with development of this after this issue. You can contact me via email (listed on my profile). Thanks!

**Comment by Ekultek** [comment]
If you have discord I can send you my discord name tomorrow, email you can send to staysalty@protonmail.com, Twitter my handle is @stay__salty. Discord is probably the best place to get ahold of me if you need to talk to me that moment

**Comment by Ekultek** [comment]
added via https://github.com/Ekultek/WhatWaf/commit/98fd390fa0964ee3bfddd1250fafb33373fd4133
