### ISSUE TITLE
New tamper 

### ISSUE THREAD

**Issue by Gentech57** [Ekultek/WhatWaf#469]
https://www.dosya.tc/server22/xz100m/Fingerprints.html

Asp net generic website firewall 
Please new tamper

**Comment by Ekultek** [comment]
Are you asking for a tamper or a waf script?

**Comment by Gentech57** [comment]
I sent mail

**Comment by Ekultek** [comment]
Do you have any idea what firewall it is?

**Comment by 687766616e** [comment]
> https://www.dosya.tc/server22/xz100m/Fingerprints.html
> 
> Asp net generic website firewall
> Please new tamper

@Ekultek tell him to hide that link, it's too many ads
@Gentech57 use Firefox send?
