### ISSUE TITLE
join forces

### ISSUE THREAD

**Issue by blshkv** [Ekultek/WhatWaf#627]
https://github.com/EnableSecurity/wafw00f/issues/87
thanks

**Comment by Ekultek** [comment]
@blshkv I emailed them not too long ago and they never replied, I was just assuming they weren’t interested. I would very much enjoy the opportunity to work with them, I think it would make both our projects blow everything else out of the water. Thanks for opening the issue, looking forward to the response.

**Comment by blshkv** [comment]
Thanks!

**Comment by Ekultek** [comment]
Anytime man!
