### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by Hume3** [Ekultek/WhatWaf#66]
Hi thanks for you work,

I see that I do not implement a method to perform POST queries multipart form/ JSON , and
there is no possibility to add cookies.
How would you handle a WAF with authentication bypass test?

Do you plan to add these features 🤔?

**Comment by Ekultek** [comment]
Hi, yes there is a plan to implement POST. As for multipart not so much, cookies could be implemented. If you feel that multi part is a functionality that needs to be delivered feel free to make a PR for it.

POST will be implemented, I’ve just been busy doing other things

**Comment by Ekultek** [comment]
As of https://github.com/Ekultek/WhatWaf/commit/a297915f1a279abd7e81310346c7e31671b6f53d you can now provide your own headers (IE Cookies or Set-Cookies). To do this you need to provide the headers in the following format: Header=Value,Header=Value,Header=Value...

I'll wait for your reply to get started on the other things you mentioned, give me some reasons to implement forms and it might happen.

**Comment by Ekultek** [comment]
@Hume3 can you provide a firewall that has a authentication bypass?

**Comment by Ekultek** [comment]
As of https://github.com/Ekultek/WhatWaf/commit/cbc21d375e9c35d2117cc3780a47a35423aa52d1 whatwaf can now make post requests and parse Burp request files
