### ISSUE TITLE
WatchGuard waf

### ISSUE THREAD

**Issue by h0nus** [Ekultek/WhatWaf#660]
This WAF is missing if your WAF list,
for help there is how to detect it:

Detection Methodology:
- `Server` headers may contain `WatchGuard` field value.
- Blocked response page contains:
  - `Request denied by WatchGuard Firewall` text.
  - `WatchGuard Technologies Inc.` as footer.

**Comment by Ekultek** [comment]
Thank you ♥️

**Comment by h0nus** [comment]
hi, i'm testing it and the tool doesn't find it and says it's an unknow Fingerprint, even if the regex should work.
In debug i've seen that some checks are not done (also watchguard) and are skipped but only loaded.
 Should i open a new issue?

**Comment by h0nus** [comment]
By the way i wanted to thank you for the awesome project!!

**Comment by h0nus** [comment]
Here i'll leave you the screen of a updated whatwaf re-downloaded from git clone.

![image](https://user-images.githubusercontent.com/23401728/71127156-caff1500-21ea-11ea-8fca-367a1969e185.png)

It seems to be loading it, but in the end it won't use it.
