### ISSUE TITLE
Some  modules won't be used even if loaded

### ISSUE THREAD

**Issue by h0nus** [Ekultek/WhatWaf#662]
Here i'll leave you the screen of a updated whatwaf re-downloaded from git clone.

![image](https://user-images.githubusercontent.com/23401728/71127156-caff1500-21ea-11ea-8fca-367a1969e185.png)

It seems to be loading it, but in the end it won't use it.

Here there is an example of a plugin loaded&used:

![image](https://user-images.githubusercontent.com/23401728/71127267-0d285680-21eb-11ea-866d-05248122fdfe.png)

_Originally posted by @h0nus in https://github.com/Ekultek/WhatWaf/issues/660#issuecomment-567233425_

**Comment by Ekultek** [comment]
I removed the "running module" string from the code https://github.com/Ekultek/WhatWaf/blob/master/content/__init__.py#L49

**Comment by Ekultek** [comment]
If there's an error while running it, it will output the error: https://github.com/Ekultek/WhatWaf/blob/master/content/__init__.py#L557

**Comment by Ekultek** [comment]
I can't reproduce this:
```
./whatwaf -u "https://google.com" --skip --verbose | grep -i "bigip"
[12:27:34][DEBUG] loading plugin script 'bigip'
[12:27:34][DEBUG] running <module 'content.plugins.bigip' from '/home/loki/bin/work/whatwaf/content/plugins/bigip.pyc'>
[12:27:34][DEBUG] running <module 'content.plugins.bigip' from '/home/loki/bin/work/whatwaf/content/plugins/bigip.pyc'>
[12:27:35][DEBUG] running <module 'content.plugins.bigip' from '/home/loki/bin/work/whatwaf/content/plugins/bigip.pyc'>
[12:27:35][DEBUG] running <module 'content.plugins.bigip' from '/home/loki/bin/work/whatwaf/content/plugins/bigip.pyc'>
```

```
./whatwaf -u "https://google.com" --skip --verbose | grep -i "watchguard"
[12:27:55][DEBUG] loading plugin script 'watchguard'
[12:27:55][DEBUG] running <module 'content.plugins.watchguard' from '/home/loki/bin/work/whatwaf/content/plugins/watchguard.pyc'>
[12:27:55][DEBUG] running <module 'content.plugins.watchguard' from '/home/loki/bin/work/whatwaf/content/plugins/watchguard.pyc'>
[12:27:56][DEBUG] running <module 'content.plugins.watchguard' from '/home/loki/bin/work/whatwaf/content/plugins/watchguard.pyc'>
```

Can you email me the actual URL?

**Comment by Ekultek** [comment]
I wrote a little bash command to run all the plugins and grep for the output of them 
```
for item in $(ls content/plugins | grep -v pyc | grep -v __init__ | cut -d '.' -f1); do echo -e "\nchecking for $item\n" && ./whatwaf -u https://google.com --skip --verbose -t 9 --ra | grep -i $item; done >> all_ran_results.txt
```
Results are attached. Everything ran as expected. 
[all_ran_results.txt](https://github.com/Ekultek/WhatWaf/files/3985258/all_ran_results.txt)

**Comment by Ekultek** [comment]
Sorry my account got flagged, it’s back up now @h0nus

**Comment by h0nus** [comment]
Ooooh, that's why i wasn't able to find you anywhere on github ahaha
I was thinking about your quit.
By the way i'll test again and i'll send it over to you! 
Cheers.

**Comment by h0nus** [comment]
PS. did you try the grep -i command with watchguard?

**Comment by Ekultek** [comment]
@h0nus if you look at the results from the script, everything is loaded and ran as normal

**Comment by h0nus** [comment]
Actually as I've let you see, the watchguard plugin doesn't load.
PS: i forgot what website had this firewall so at the moment i can't give you any other feedback.
The main problem was that the "watchguard" checks doesn't start, but is only loaded.

**Comment by Ekultek** [comment]
![6BCA3EF4-B5C9-480E-9358-2E29ACA7E18E](https://user-images.githubusercontent.com/14183473/71651606-96a85000-2ce4-11ea-9801-82c6a1e67913.jpeg)

As shown in the script above results text file, it’s loading just fine. There is a thing where if there’s an error loading the script it just skips it, that could be the issue for you

**Comment by h0nus** [comment]
Uhm, ok, i'll check again. Thanks for help.
Closing issue for now, if the problem persist, i'll open it again.
Thanks and congrats again for the awesome tool :)
