### ISSUE TITLE
 error message 

### ISSUE THREAD

**Issue by hinokop** [Ekultek/WhatWaf#72]
[FATAL] WhatWaf has caught an unhandled exception with the error message: ''>' not supported between instances of 'NoneType' and 'int''. 

?

**Comment by Ekultek** [comment]
All the output of the instance, and the full cmd line ran please

**Comment by Ekultek** [comment]
Hi if you could do me a favor and update to the latest version, it will now output the traceback and some other information I will need in order to replicate the issue. Go ahead and update and re-run it, please, and thank you

**Comment by Ekultek** [comment]
dupe #76
