### ISSUE TITLE
WhatWaf has caught an unhandled exception with the error message: 'list index out of range'

### ISSUE THREAD

**Issue by fcafra** [Ekultek/WhatWaf#75]
Hi, 
IM running the lastest version.

uname -a
Linux <name> 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux

When I launch with --proxy http://127.0.0.1:9050 and [SUCCESS] no protection identified on target
but
When I launch without proxy option
[SUCCESS] detected website protection identified as 'Apache generic website protection', searching for bypasses
[INFO] loading payload tampering scripts
[INFO] running tampering bypass checks
[SUCCESS] apparent working tampers for target:

(#69) description: tamper payload by implanting random comments into the payload
example: '' AND 1=1 ' OR 10=11,<s/**/c/**/ript>ale/**/rt('');<//**/scr/**/ipt>'
load path: content.tampers.randomcomments

[FATAL] WhatWaf has caught an unhandled exception with the error message: 'list index out of range'. You can create an issue here: 'https://github.com/Ekultek/WhatWaf/issues/new'

**Comment by Ekultek** [comment]
please send the URL and full command line options to staysalty@protonmail.com

Thank you

**Comment by Ekultek** [comment]
@fcafra Hi if you could do me a favor and update to the latest version, it will now output the traceback and some other information I will need in order to replicate the issue. Go ahead and update and re-run it, please, and thank you

**Comment by fcafra** [comment]
Hi @Ekultek,

Thanks for your Response.  I send you an email with full details.  Thanks !
