### ISSUE TITLE
windows os port

### ISSUE THREAD

**Issue by hastalamuerte** [Ekultek/WhatWaf#896]
Can you make plz a windows os version?

**Comment by Ekultek** [comment]
This should work on windows already

**Comment by hastalamuerte** [comment]
Cant install it 
allready install MS visual c++ with all packets)) 4.5 gb for whatwaf)) 
install requierments through pip

but when i run py *****/setup.py have that *
Traceback (most recent call last):
  File "C:\Users\4\Desktop\WhatWaf-master\setup.py", line 17, in <module>
    needs_username_fix = os.getuid() == 0
AttributeError: module 'os' has no attribute 'getuid'

+ python3 C:\Users\4\Desktop\WhatWaf-master\setup.py
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by hastalamuerte** [comment]
Maybe something like this 
if os_type == OS_WINDOWS:
		import ctypes
		if ctypes.windll.shell32.IsUserAnAdmin():
			return True
		else:
			return False 
will help

**Comment by mxmsec** [comment]
Hello you can run it on windows ?
i have same problem
