### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by zencharcoal** [Ekultek/WhatWaf#940]
As you can see I have installed requests; however, I am still receiving an error "stating that no module named requests" exists.
kali@kali:~/WhatWaf$ python3 -m pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.23.0)
kali@kali:~/WhatWaf$ ./whatwaf 
Traceback (most recent call last):
  File "./whatwaf", line 3, in <module>
    from trigger.main import main
  File "/home/kali/WhatWaf/trigger/main.py", line 7, in <module>
    from lib.miner import Miner
  File "/home/kali/WhatWaf/lib/miner/__init__.py", line 17, in <module>
    import lib.settings
  File "/home/kali/WhatWaf/lib/settings.py", line 19, in <module>
    import requests
ImportError: No module named requests
kali@kali:~/WhatWaf$ 

Perhaps because requests is not a module. 
kali@kali:~/WhatWaf$ python3 -m requests
/usr/bin/python3: No module named requests.__main__; 'requests' is a package and cannot be directly executed
kali@kali:~/WhatWaf$ 

Can you advise?

**Comment by Ekultek** [comment]
pip install -r requirements.txt
