### ISSUE TITLE
Amount of requests count

### ISSUE THREAD

**Issue by Ekultek** [Ekultek/WhatWaf#97]
I feel like there should be an “amount of requests sent” counter. This should be pretty simple

**Comment by ZacharyGroff** [comment]
What do you want done with this counter? Should it be printed to console? Just once at the end? Or after every x requests? Should an additional command line argument be added to toggle this?

**Comment by Ekultek** [comment]
@ZacharyGroff I was thinking just output it to the console at the end after everything has done as an info message. If you wanted to you could add another command line arg like —count or something. I’m pretty open to this one

**Comment by Ekultek** [comment]
@ZacharyGroff _if_ you're working on this, I'm about to update to 0.9, so be sure to pull before you push

**Comment by ZacharyGroff** [comment]
@Ekultek I'll be pulling and working on this in ~6 hours so no worries.

**Comment by Ekultek** [comment]
@ZacharyGroff Cool man, thank you ahead of time!

**Comment by ZacharyGroff** [comment]
@Ekultek If an exception is thrown in whatwaf/main.py , do you think an info message should be logged with the number of requests sent before the exception was thrown? If this is the case, it seems like this would require a bit more work than if request count was only logged when main exits successfully. Just curious what your preference would be before I implement it one way or the other.

**Comment by Ekultek** [comment]
@ZacharyGroff if an exception is thrown we should skip it and throw the exception

**Comment by Ekultek** [comment]
Thanks for the help!
