### ISSUE TITLE
shell

### ISSUE THREAD

**Issue by hastalamuerte** [Ekultek/WhatWaf#978]
Hello, plz add a shell menu for work in win os with pwshll or cmd. 
like (--sqlmap-shell)  it will really help and save time 
for sqlmap i made a bat 
*C:
cd C:\Users\\Desktop\sqlmap-master
cls
sqlmap.py --sqlmap-shell
* 
and it very easy to work with. 
Thx for your work

**Comment by hastalamuerte** [comment]
also plz look https://github.com/Ekultek/WhatWaf/issues/896#issuecomment-735018261 there is a problem with windows installation

**Comment by Ekultek** [comment]
Windows doesn’t have a suid of 0 because I doesn’t have a root user to answer your install question, run it as a stand-alone script from inside the download directory. I’m not sure what you mean by shell menu?

**Comment by hastalamuerte** [comment]
> 
> 
> Windows doesn’t have a suid of 0 because it doesn’t have a root user to answer your install question, run it as a stand-alone >script from inside the download directory. I’m not sure what you mean by shell menu?

**-shell comand... like *no exit (from cmd zsh pwsh) and wait for another comand with 0 activity after ending previos command maybe with some indication of shell menu https://prnt.sc/wbzvkl  (sqlmap example) ***

thank for you work . will try to init whatwaf to pentestbox on win  (on lin everything is Good )

**Comment by Ekultek** [comment]
Idk what sqlmap shell does, I don’t use it very often. Is it just a terminal to do everything manually?

**Comment by mxmsec** [comment]
* same problem i cant install it on windows server 2019..
* what i can do please ?
